### ISSUE TITLE
Zaciąganie obrazków (i może przy okazji jsonów)

### ISSUE THREAD

**Issue by gizlu** [marcinwozniak0/BakcylProgramowania_2020#78]
Miałem dwa pomysły:
- zaciąganie obrazków just in time - pobieramy tylko to, co widzi użytkownik
- zaciąganie wszystkich obrazków z góry przy pierwszym starcie programu (albo aktualizacji assetów)

Zrobiłem kilka eksperymentów i tak
- pierwsza opcja jest w zasadzie nieużywalna:
   - na lepszym internecie zaciąganie 30 obrazków osobno trwa z 1 do 3 sekund - Niezbyt dobrze, ale tolerowalnie
   - na słabszym internecie zaciąganie 30 obrazów trwa nawet 15 sekund co czyni tę opcję praktycznie nieużywalną

- Pobieranie 4 zipów z wszystkimi (tymi uproszczonymi, z samymi kartami bez "tapet") assetami wydłuża znacznie czas pierwszego startu (i aktualizacji) oraz zużywa więcej miejsca (736.9MB rozpakowane, 735.1 MB zapakowane), ale w ogólnym rozrachunku jest bardziej tolerowalna
   - przy szybszym połączeniu trwa to około 20 sekund - super
   - przy słabszym połączeniu trwa to około 7.5 minut - słabo, ale więcej ma to sensu niż 15 sekund co wyszukanie

Wszystko testowałem przy użyciu `curl --remote-name-all --parallel <lista linków>`. Nie dostarczam nawet wyników bez `--parallel` gdyż są tragiczne. Prawdopodobnie do pobierania będziemy wykorzystywać libcurla, który oferuje interfejs `multi`, który jest asynchroniczny (nie blokuje wątku więc nie trzeba spawnować kilku) i powinien mieć porównywalne wyniki co `curl --parallel`

Dodatkowo można dodać użytkownikowi opcję, która oszczędza czas, transfer i dysk nie pokazując żadnych obrazków - raczej najprostsza i najsensowniejsza w implementacji alternatywa dla batcha (tak mi się wydaje, na szczęście nie znam się na UI), i pewnie trzeba będzie zrobić osobny interfejs specjalnie pod to. @QT nie musi być to nawet jakoś perfekcyjne, na początek wystarczy nawet to samo UI z placeholderami zamiast assetów) 

Zrobienie porządnego downloadera na `libcurl multi` powinno rozwiązać pobieranie obrazków jak i jsonów

Na branchu [DownloadingJsonFiles](https://github.com/marcinwozniak0/BakcylProgramowania_2020/tree/DownloadingJsonFiles) w plikach [filedownloader.h](https://github.com/marcinwozniak0/BakcylProgramowania_2020/compare/DownloadingJsonFiles#diff-f6347a72bbff6be01a4c6d55931d8bb8260f4600c74ac0853bc4a6f5f2747941) i [filedownloader.cpp](https://github.com/marcinwozniak0/BakcylProgramowania_2020/compare/DownloadingJsonFiles#diff-a93935d5631b30bca78ee4bf65819256b5962ef4386b9adfac10a52a1053a23b) znajduje się jakaś prototypowa implementacja downloadera na `libcurl easy` wykonana przez @Adziwiszek. Można tego jakoś użyć do zrobienia pełnego downloadera na `libcurl multi`

stara treść tego ticketa:
> Oddelegować mechanizm pobierania obrazków logice. Co prawda bardziej zadanie dla logiki, ale zastanwiałem się jak
> zaprojektować api i zrobiłem kilka eksperymentów. Założę im jakiś issue z obserwacjami i propozycjami. 
> Przy okazji można wykorzystać ich pracę (albo oni naszą) do pobierania jsonów

**Comment by szaranczuk** [comment]
@Adziwiszek i @kHuryn zgłosili się do tego zadania

**Comment by Adziwiszek** [comment]
zmergowałem brancha z downloaderem do maina
